### ISSUE TITLE
Error while creating react app, please help

### ISSUE THREAD

**Issue by p-rocker** [p-rocker/SampleReactDemo#1]
Installing template dependencies using npm...
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path E:\myreactapps\appdemo\my-app-d\node_modules\.staging
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'E:\myreactapps\appdemo\my-app-d\node_modules\.staging'
npm ERR!  [Error: EPERM: operation not permitted, unlink 'E:\myreactapps\appdemo\my-app-d\node_modules\.staging'] {
npm ERR!   stack: "Error: EPERM: operation not permitted, unlink 'E:\\myreactapps\\appdemo\\my-app-d\\node_modules\\.staging'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'E:\\myreactapps\\appdemo\\my-app-d\\node_modules\\.staging'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pRaDeep\AppData\Roaming\npm-cache\_logs\2019-12-15T06_20_48_462Z-debug.log
`npm install --save @testing-library/react@^9.3.2 @testing-library/jest-dom@^4.2.4 @testing-library/user-event@^7.1.2` failed
C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:313
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\pRaDeep\AppData\Roaming\npm-cache\_npx\14260\node_modules\create-react-app\node_modules\cross-spawn\node_modules'
    at Object.rmdirSync (fs.js:752:3)
    at rmkidsSync (C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\pRaDeep\AppData\Roaming\npm\node_modules\npm\node_modules\rimraf\rimraf.js:342:5 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\Users\\pRaDeep\\AppData\\Roaming\\npm-cache\\_npx\\14260\\node_modules\\create-react-app\\node_modules\\cross-spawn\\node_modules'
}
![err](https://user-images.githubusercontent.com/39938857/70859069-9c0b4980-1f33-11ea-9120-719944d9cf19.png)

**Comment by p-rocker** [comment]
I am building a simple react js UI but each time I'm facing this error.
NPM- v12.13.1
NPX- 6.13.4
OS -Windows 10
Framework- VSC
